version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phishguard_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - phishguard_network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: phishguard_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - phishguard_network
    depends_on:
      - app

  db:
    image: postgres:14-alpine
    container_name: phishguard_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: phishguard
      POSTGRES_USER: phishguard_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - phishguard_network
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: phishguard_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - phishguard_network
    ports:
      - "6379:6379"

networks:
  phishguard_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
